### ISSUE TITLE
the modified MIT licence and Guix (FSF)

### ISSUE THREAD

**Issue by attila-lendvai** [SamuelHaidu/simple-rlp#1]
i'm packaging trezor stuff for Guix (a linux distro). it is an FSF free software fundamentalist distro, which means that "anything restricting the basic freedoms make licenses non-free", which applies to your last sentence "This software cannot be used by state organizations.".

now, i fully agree with you... but due to this i cannot update trezor support in Guix (or at least not easily; i'd need to weed out the tests that require this lib).

and arguably, it's also too broad; i.e. it includes schools run with government money, and also not very clear where the line is between state and non-state organizations.

in these lights, would you be willing to revert to vanilla MIT?

**Comment by hegjon** [comment]
I am running into the same issue for Fedora

**Comment by prusnak** [comment]
Trezor maintainer here. I agree with the sentiment, but adding such restriction to an open-source license makes the source no longer usable and makes it unacceptable for use in other open-source projects. I strongly suggest you revert to the original wording of the MIT license.

**Comment by attila-lendvai** [comment]
@SamuelHaidu pretty please!

it would make my life so much simpler...

**Comment by attila-lendvai** [comment]
oh well, i have bad news: the last activity of the owner of this repo was from December 2021.

how shall we proceed?

**Comment by SamuelHaidu** [comment]
Hi guys, sorry for the delay. I just read the issue and I understand that maybe because it involves schools and other institutions that may even be community-based, it really doesn't seem very fair to me. I'll revert back to standard MIT license :D

**Comment by SamuelHaidu** [comment]
New version 0.1.3 avaliable on PyPI. Solved!

**Comment by prusnak** [comment]
> Solved!

Thank you, Samuel! Much appreciated
