### ISSUE TITLE
consider tagging the git repo

### ISSUE THREAD

**Issue by attila-lendvai** [SamuelHaidu/simple-rlp#2]
it helps the packagers, who don't want to trust/rely on pypi.org.

PGP signing the tags adds some extra geek value... :)

**Comment by SamuelHaidu** [comment]
`data-structures` `rlp` `etherium` `rlp-serializer` added to repo, anything else you want to suggest?

**Comment by attila-lendvai** [comment]
sorry, i meant git tags, so that e.g. Guix package descriptions can point to them (as opposed to pointing to git commits).

it's not super important, but it would be helpful.

**Comment by SamuelHaidu** [comment]
oops, I understand now. No problem, I think it's a good practice. It also makes it easier to see the code of a specific version.
 
Apparently the community is using this lib so I'm preparing new commits to improve some points. These new ones I will include git tags.
